<?php

/*
 * Copyright (C) 2015 Guo Yunhe <guoyunhebrave@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * Get an array of all countries in the world.
 * 
 * Result format:
 * ['US' => 'United States', 'FI' => 'Finland', ...]
 * 
 * @return array An array of all countries in the world
 */
function su_get_country_array() {
    $country_array = array(
        "AF" => "Afghanistan",
        "AL" => "Albania",
        "DZ" => "Algeria",
        "AS" => "American Samoa",
        "AD" => "Andorra",
        "AO" => "Angola",
        "AI" => "Anguilla",
        "AQ" => "Antarctica",
        "AG" => "Antigua and Barbuda",
        "AR" => "Argentina",
        "AM" => "Armenia",
        "AW" => "Aruba",
        "AU" => "Australia",
        "AT" => "Austria",
        "AZ" => "Azerbaijan",
        "BS" => "Bahamas",
        "BH" => "Bahrain",
        "BD" => "Bangladesh",
        "BB" => "Barbados",
        "BY" => "Belarus",
        "BE" => "Belgium",
        "BZ" => "Belize",
        "BJ" => "Benin",
        "BM" => "Bermuda",
        "BT" => "Bhutan",
        "BO" => "Bolivia",
        "BA" => "Bosnia and Herzegovina",
        "BW" => "Botswana",
        "BV" => "Bouvet Island",
        "BR" => "Brazil",
        "IO" => "British Indian Ocean Territory",
        "VG" => "British Virgin Islands",
        "BN" => "Brunei",
        "BG" => "Bulgaria",
        "BF" => "Burkina Faso",
        "BI" => "Burundi",
        "KH" => "Cambodia",
        "CM" => "Cameroon",
        "CA" => "Canada",
        "CV" => "Cape Verde",
        "KY" => "Cayman Islands",
        "CF" => "Central African Republic",
        "TD" => "Chad",
        "CL" => "Chile",
        "CN" => "China",
        "CX" => "Christmas Island",
        "CC" => "Cocos [Keeling] Islands",
        "CO" => "Colombia",
        "KM" => "Comoros",
        "CG" => "Congo - Brazzaville",
        "CD" => "Congo - Kinshasa",
        "CK" => "Cook Islands",
        "CR" => "Costa Rica",
        "HR" => "Croatia",
        "CU" => "Cuba",
        "CY" => "Cyprus",
        "CZ" => "Czech Republic",
        "CI" => "Côte d’Ivoire",
        "DK" => "Denmark",
        "DJ" => "Djibouti",
        "DM" => "Dominica",
        "DO" => "Dominican Republic",
        "EC" => "Ecuador",
        "EG" => "Egypt",
        "SV" => "El Salvador",
        "GQ" => "Equatorial Guinea",
        "ER" => "Eritrea",
        "EE" => "Estonia",
        "ET" => "Ethiopia",
        "FK" => "Falkland Islands",
        "FO" => "Faroe Islands",
        "FJ" => "Fiji",
        "FI" => "Finland",
        "FR" => "France",
        "GF" => "French Guiana",
        "PF" => "French Polynesia",
        "TF" => "French Southern Territories",
        "GA" => "Gabon",
        "GM" => "Gambia",
        "GE" => "Georgia",
        "DE" => "Germany",
        "GH" => "Ghana",
        "GI" => "Gibraltar",
        "GR" => "Greece",
        "GL" => "Greenland",
        "GD" => "Grenada",
        "GP" => "Guadeloupe",
        "GU" => "Guam",
        "GT" => "Guatemala",
        "GG" => "Guernsey",
        "GN" => "Guinea",
        "GW" => "Guinea-Bissau",
        "GY" => "Guyana",
        "HT" => "Haiti",
        "HM" => "Heard Island and McDonald Islands",
        "HN" => "Honduras",
        "HK" => "Hong Kong SAR China",
        "HU" => "Hungary",
        "IS" => "Iceland",
        "IN" => "India",
        "ID" => "Indonesia",
        "IR" => "Iran",
        "IQ" => "Iraq",
        "IE" => "Ireland",
        "IM" => "Isle of Man",
        "IL" => "Israel",
        "IT" => "Italy",
        "JM" => "Jamaica",
        "JP" => "Japan",
        "JE" => "Jersey",
        "JO" => "Jordan",
        "KZ" => "Kazakhstan",
        "KE" => "Kenya",
        "KI" => "Kiribati",
        "KW" => "Kuwait",
        "KG" => "Kyrgyzstan",
        "LA" => "Laos",
        "LV" => "Latvia",
        "LB" => "Lebanon",
        "LS" => "Lesotho",
        "LR" => "Liberia",
        "LY" => "Libya",
        "LI" => "Liechtenstein",
        "LT" => "Lithuania",
        "LU" => "Luxembourg",
        "MO" => "Macau SAR China",
        "MK" => "Macedonia",
        "MG" => "Madagascar",
        "MW" => "Malawi",
        "MY" => "Malaysia",
        "MV" => "Maldives",
        "ML" => "Mali",
        "MT" => "Malta",
        "MH" => "Marshall Islands",
        "MQ" => "Martinique",
        "MR" => "Mauritania",
        "MU" => "Mauritius",
        "YT" => "Mayotte",
        "MX" => "Mexico",
        "FM" => "Micronesia",
        "MD" => "Moldova",
        "MC" => "Monaco",
        "MN" => "Mongolia",
        "ME" => "Montenegro",
        "MS" => "Montserrat",
        "MA" => "Morocco",
        "MZ" => "Mozambique",
        "MM" => "Myanmar [Burma]",
        "NA" => "Namibia",
        "NR" => "Nauru",
        "NP" => "Nepal",
        "NL" => "Netherlands",
        "AN" => "Netherlands Antilles",
        "NC" => "New Caledonia",
        "NZ" => "New Zealand",
        "NI" => "Nicaragua",
        "NE" => "Niger",
        "NG" => "Nigeria",
        "NU" => "Niue",
        "NF" => "Norfolk Island",
        "KP" => "North Korea",
        "MP" => "Northern Mariana Islands",
        "NO" => "Norway",
        "OM" => "Oman",
        "PK" => "Pakistan",
        "PW" => "Palau",
        "PS" => "Palestinian Territories",
        "PA" => "Panama",
        "PG" => "Papua New Guinea",
        "PY" => "Paraguay",
        "PE" => "Peru",
        "PH" => "Philippines",
        "PN" => "Pitcairn Islands",
        "PL" => "Poland",
        "PT" => "Portugal",
        "PR" => "Puerto Rico",
        "QA" => "Qatar",
        "RO" => "Romania",
        "RU" => "Russia",
        "RW" => "Rwanda",
        "RE" => "Réunion",
        "BL" => "Saint Barthélemy",
        "SH" => "Saint Helena",
        "KN" => "Saint Kitts and Nevis",
        "LC" => "Saint Lucia",
        "MF" => "Saint Martin",
        "PM" => "Saint Pierre and Miquelon",
        "VC" => "Saint Vincent and the Grenadines",
        "WS" => "Samoa",
        "SM" => "San Marino",
        "SA" => "Saudi Arabia",
        "SN" => "Senegal",
        "RS" => "Serbia",
        "SC" => "Seychelles",
        "SL" => "Sierra Leone",
        "SG" => "Singapore",
        "SK" => "Slovakia",
        "SI" => "Slovenia",
        "SB" => "Solomon Islands",
        "SO" => "Somalia",
        "ZA" => "South Africa",
        "GS" => "South Georgia and the South Sandwich Islands",
        "KR" => "South Korea",
        "ES" => "Spain",
        "LK" => "Sri Lanka",
        "SD" => "Sudan",
        "SR" => "Suriname",
        "SJ" => "Svalbard and Jan Mayen",
        "SZ" => "Swaziland",
        "SE" => "Sweden",
        "CH" => "Switzerland",
        "SY" => "Syria",
        "ST" => "São Tomé and Príncipe",
        "TW" => "Taiwan",
        "TJ" => "Tajikistan",
        "TZ" => "Tanzania",
        "TH" => "Thailand",
        "TL" => "Timor-Leste",
        "TG" => "Togo",
        "TK" => "Tokelau",
        "TO" => "Tonga",
        "TT" => "Trinidad and Tobago",
        "TN" => "Tunisia",
        "TR" => "Turkey",
        "TM" => "Turkmenistan",
        "TC" => "Turks and Caicos Islands",
        "TV" => "Tuvalu",
        "UM" => "U.S. Minor Outlying Islands",
        "VI" => "U.S. Virgin Islands",
        "UG" => "Uganda",
        "UA" => "Ukraine",
        "AE" => "United Arab Emirates",
        "GB" => "United Kingdom",
        "US" => "United States",
        "UY" => "Uruguay",
        "UZ" => "Uzbekistan",
        "VU" => "Vanuatu",
        "VA" => "Vatican City",
        "VE" => "Venezuela",
        "VN" => "Vietnam",
        "WF" => "Wallis and Futuna",
        "EH" => "Western Sahara",
        "YE" => "Yemen",
        "ZM" => "Zambia",
        "ZW" => "Zimbabwe",
        "AX" => "Åland Islands",
    );
    return $country_array;
}

function su_get_country_three_letter_array() {
    $country_array = array(
        "AF" => "AFG",
        "AL" => "ALB",
        "DZ" => "DZA",
        "AS" => "ASM",
        "AD" => "AND",
        "AO" => "AGO",
        "AI" => "AIA",
        "AQ" => "ATA",
        "AG" => "ATG",
        "AR" => "ARG",
        "AM" => "ARM",
        "AW" => "ABW",
        "AU" => "AUS",
        "AT" => "AUT",
        "AZ" => "AZE",
        "BS" => "BHS",
        "BH" => "BHR",
        "BD" => "BGD",
        "BB" => "BRB",
        "BY" => "BLR",
        "BE" => "BEL",
        "BZ" => "BLZ",
        "BJ" => "BEN",
        "BM" => "BMU",
        "BT" => "BTN",
        "BO" => "BOL",
        "BA" => "BIH",
        "BW" => "BWA",
        "BV" => "BVT",
        "BR" => "BRA",
        "IO" => "IOT",
        "VG" => "VGB",
        "BN" => "BRN",
        "BG" => "BGR",
        "BF" => "BFA",
        "BI" => "BDI",
        "KH" => "KHM",
        "CM" => "CMR",
        "CA" => "CAN",
        "CV" => "CPV",
        "KY" => "CYM",
        "CF" => "CAF",
        "TD" => "TCD",
        "CL" => "CHL",
        "CN" => "CHN",
        "CX" => "CXR",
        "CC" => "CCK",
        "CO" => "COL",
        "KM" => "COM",
        "CG" => "COG",
        "CD" => "COD",
        "CK" => "COK",
        "CR" => "CRI",
        "HR" => "HRV",
        "CU" => "CUB",
        "CY" => "CYP",
        "CZ" => "CZE",
        "CI" => "CIV",
        "DK" => "DNK",
        "DJ" => "DJI",
        "DM" => "DMA",
        "DO" => "DOM",
        "EC" => "ECU",
        "EG" => "EGY",
        "SV" => "SLV",
        "GQ" => "GNQ",
        "ER" => "ERI",
        "EE" => "EST",
        "ET" => "ETH",
        "FK" => "FLK",
        "FO" => "FRO",
        "FJ" => "FJI",
        "FI" => "FIN",
        "FR" => "FRA",
        "GF" => "GUF",
        "PF" => "PYF",
        "TF" => "ATF",
        "GA" => "GAB",
        "GM" => "GMB",
        "GE" => "GEO",
        "DE" => "DEU",
        "GH" => "GHA",
        "GI" => "GIB",
        "GR" => "GRC",
        "GL" => "GRL",
        "GD" => "GRD",
        "GP" => "GLP",
        "GU" => "GUM",
        "GT" => "GTM",
        "GG" => "GGY",
        "GN" => "GIN",
        "GW" => "GNB",
        "GY" => "GUY",
        "HT" => "HTI",
        "HM" => "HMD",
        "HN" => "HND",
        "HK" => "HKG",
        "HU" => "HUN",
        "IS" => "ISL",
        "IN" => "IND",
        "ID" => "IDN",
        "IR" => "IRN",
        "IQ" => "IRQ",
        "IE" => "IRL",
        "IM" => "IMN",
        "IL" => "ISR",
        "IT" => "ITA",
        "JM" => "JAM",
        "JP" => "JPN",
        "JE" => "JEY",
        "JO" => "JOR",
        "KZ" => "KAZ",
        "KE" => "KEN",
        "KI" => "KIR",
        "KW" => "KWT",
        "KG" => "KGZ",
        "LA" => "LAO",
        "LV" => "LVA",
        "LB" => "LBN",
        "LS" => "LSO",
        "LR" => "LBR",
        "LY" => "LBY",
        "LI" => "LIE",
        "LT" => "LTU",
        "LU" => "LUX",
        "MO" => "MAC",
        "MK" => "MKD",
        "MG" => "MDG",
        "MW" => "MWI",
        "MY" => "MYS",
        "MV" => "MDV",
        "ML" => "MLI",
        "MT" => "MLT",
        "MH" => "MHL",
        "MQ" => "MTQ",
        "MR" => "MRT",
        "MU" => "MUS",
        "YT" => "MYT",
        "MX" => "MEX",
        "FM" => "FSM",
        "MD" => "MDA",
        "MC" => "MCO",
        "MN" => "MNG",
        "ME" => "MNE",
        "MS" => "MSR",
        "MA" => "MAR",
        "MZ" => "MOZ",
        "MM" => "MMR",
        "NA" => "NAM",
        "NR" => "NRU",
        "NP" => "NPL",
        "NL" => "NLD",
        "AN" => "ANT",
        "NC" => "NCL",
        "NZ" => "NZL",
        "NI" => "NIC",
        "NE" => "NER",
        "NG" => "NGA",
        "NU" => "NIU",
        "NF" => "NFK",
        "KP" => "PRK",
        "MP" => "MNP",
        "NO" => "NOR",
        "OM" => "OMN",
        "PK" => "PAK",
        "PW" => "PLW",
        "PS" => "PSE",
        "PA" => "PAN",
        "PG" => "PNG",
        "PY" => "PRY",
        "PE" => "PER",
        "PH" => "PHL",
        "PN" => "PCN",
        "PL" => "POL",
        "PT" => "PRT",
        "PR" => "PRI",
        "QA" => "QAT",
        "RO" => "ROU",
        "RU" => "RUS",
        "RW" => "RWA",
        "RE" => "REU",
        "BL" => "BLM",
        "SH" => "SHN",
        "KN" => "KNA",
        "LC" => "LCA",
        "MF" => "MAF",
        "PM" => "SPM",
        "VC" => "VCT",
        "WS" => "WSM",
        "SM" => "SMR",
        "SA" => "SAU",
        "SN" => "SEN",
        "RS" => "SRB",
        "SC" => "SYC",
        "SL" => "SLE",
        "SG" => "SGP",
        "SK" => "SVK",
        "SI" => "SVN",
        "SB" => "SLB",
        "SO" => "SOM",
        "ZA" => "ZAF",
        "GS" => "SGS",
        "KR" => "KOR",
        "ES" => "ESP",
        "LK" => "LKA",
        "SD" => "SDN",
        "SR" => "SUR",
        "SJ" => "SJM",
        "SZ" => "SWZ",
        "SE" => "SWE",
        "CH" => "CHE",
        "SY" => "SYR",
        "ST" => "STP",
        "TW" => "TWN",
        "TJ" => "TJK",
        "TZ" => "TZA",
        "TH" => "THA",
        "TL" => "TLS",
        "TG" => "TGO",
        "TK" => "TKL",
        "TO" => "TON",
        "TT" => "TTO",
        "TN" => "TUN",
        "TR" => "TUR",
        "TM" => "TKM",
        "TC" => "TCA",
        "TV" => "TUV",
        "UM" => "UMI",
        "VI" => "VIR",
        "UG" => "UGA",
        "UA" => "UKR",
        "AE" => "ARE",
        "GB" => "GBR",
        "US" => "USA",
        "UY" => "URY",
        "UZ" => "UZB",
        "VU" => "VUT",
        "VA" => "VAT",
        "VE" => "VEN",
        "VN" => "VNM",
        "WF" => "WLF",
        "EH" => "ESH",
        "YE" => "YEM",
        "ZM" => "ZMB",
        "ZW" => "ZWE",
        "AX" => "ALA",
    );
    return $country_array;
}

function su_get_country_name($two_letter) {
    $countrys = su_get_country_array();
    return $countrys[$two_letter];
}

function su_get_country_three_letter($two_letter) {
    $countrys = su_get_country_three_letter_array();
    return $countrys[$two_letter];
}

/**
 * Get HTML select element of all countries in the world
 * 
 * @param string $selected Selected country code, eg. 'US', 'FI', 'CN'
 */
function su_get_country_select($selected = false, $name='country', $class='', $id='') {
    $country_array = su_get_country_array();
    require __DIR__ . '/../view/country-select.php';
}

function su_get_user_country_city_list() {
    $args = [];
    $users = get_users();
    
    $countries = [];
    
    foreach ($users as $user) {
        $country = get_user_meta($user->ID, 'live_country', true);
        $city = get_user_meta($user->ID, 'live_city', true);
        if(empty($country) || empty(su_get_country_name($country)) || empty($city)) {
            continue;
        }
        if (!isset($countries[$country])) {
            $countries[$country] = [
                'name' => su_get_country_name($country),
                'three_letter' => su_get_country_three_letter($country),
                'cities' => [],
            ];
        }
        if (!in_array($city, $countries[$country]['cities'])) {
            $countries[$country]['cities'][] = $city;
        }
    }
    return $countries;
}